name: Makefile CI

on: [push, pull_request]

jobs:
  build:

    environment:
      name: testing

    env:
      DATABASE_HOST: ${{secrets.DATABASE_HOST}}
      DATABASE_NAME: ${{secrets.DATABASE_NAME}}
      DATABASE_USER: ${{secrets.DATABASE_USER}}
      DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}

    runs-on: ubuntu-latest

    steps:
      - name: pull git repo
        uses: actions/checkout@v4

      - name: set up virtual environment
        run: make venv

      - name: install dependencies
        run: make setup

      - name: check format
        run: make lint

      - name: test with pytest
        run: make test
      
      - name: login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/short_url:2
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: image digest
        run: echo ${{ steps.docker_build.outputs.digest }}