name: Makefile CI

on: [push, pull_request]

jobs:
  build:

    environment:
      name: testing

    env:
      DATABASE_HOST: ${{secrets.DATABASE_HOST}}
      DATABASE_NAME: ${{secrets.DATABASE_NAME}}
      DATABASE_USER: ${{secrets.DATABASE_USER}}
      DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}

    runs-on: ubuntu-latest

    steps:
      - name: pulling git repo
        uses: actions/checkout@v4

      - name: set up virtual environment
        run: make venv

      - name: install dependencies
        run: make setup

      - name: check format
        run: make lint

      - name: test with pytest
        run: make test